Enable coin type for ecosystem chains
cosmos/ledger-cosmos pull request #42
Opened 2022-01-06 02:47 UTC by liangping

Enable coin type for ecosystem chains which do not use 118. like desmos 852,  Band 494, Luna: 330

2022-01-06 03:15 UTC, liangping commented
@jleni What do you think of this PR? It's very useful for https://ping.pub/wallet

2022-01-09 21:55 UTC, Tomas-Eminger commented
Does this commit also enable coin type 60 for EVMOS?

2022-01-14 01:52 UTC, liangping commented
> Does this commit also enable coin type 60 for EVMOS?

I think so.

2022-02-12 18:11 UTC, jleni commented
This PR may result in problem with Ledger publication process. 

This is not the only place that you should be modified.

The most important place is here: https://github.com/cosmos/ledger-cosmos/blob/b0f39ef0715dad67fa8fcb5a21205d4b35802b02/app/Makefile#L63

Ledger uses this value to cryptographically sign and restrict the production app to only derive 44'/118'

They do this to avoid having apps deriving the keys of other chains. For example, having Cosmos signing ethereum or bitcoin txs. We can try to discuss this with Ledger and allow multiple values.. but removing the restriction completely will probably not be accepted. 

An alternative that is being discussed is to use a completely different FIRST value for cosmos SDK chains.

2022-02-12 18:13 UTC, jleni requested changes
Needs to be discussed/approved by Ledger

2022-02-12 18:14 UTC, jleni commented
@ainhoa-a can we put this in the agenda for our periodic discussion with Ledger?

2022-02-14 20:02 UTC, liangping commented
> @ainhoa-a can we put this in the agenda for our periodic discussion with Ledger?

Would be great if this PR is accept. I think it also improve user experience of Ledger.  As cosmos ecosystem booming, We need a simple way to allow users to sign transactions for those new projects.

2022-02-14 20:33 UTC, liangping commented
FYI, 60' is also used on EVM compatible chains, like EVMOS. So we'd better to restrict by address pattern than coin type.

2022-03-17 22:42 UTC, fedekunze commented
> FYI, 60' is also used on EVM compatible chains, like EVMOS. So we'd better to restrict by address pattern than coin type.

We don't use the cosmos ledger app because the key derivation is different. Only Ledger Ethereum app is supported on Evmos

2022-03-18 02:37 UTC, liangping commented
@fedekunze Thanks for clarifying.

2022-03-25 07:02 UTC, Anmol1696 commented
@jleni any updates on talks with Ledger about this? If there are some minutes in place, i would be interested in looking at it.

2022-08-04 12:06 UTC, kwunyeung commented
@liangping @jleni I don't think this is possible as this is a general restriction for all Ledger apps. This is why we had to fork the repo and deployed a separate app for `Desmos`. The current `Cosmos` app is actually an `ATOM` app. The confusion makes many wallets not aligning to the key generation for different coins which creates a very bad UX and that's why `Confio` created [this proposal](https://github.com/confio/cosmos-hd-key-derivation-spec).

2022-08-05 15:32 UTC, liangping commented
I think this `general restriction drawback of product strategy since the storage of Ledger is very limited.  That means it's not possible for users to install more than 20 apps in one device: Nano S  3, Nano X 10+.

The goal of the proposal is good. could be temp solution for Ledger, but it also bring incompatible to BIP proposals. 

By the way,  The current hardware wallet products will be replaced with TEE wallets on mobile phone in next few years.

2022-08-06 14:28 UTC, kwunyeung commented
@liangping agree and that's why a `Cosmos` app is more favourable than an `ATOM` app. The proposal actually aligns with [BIP43](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki). This is also how `Cardano` does with their [scheme](https://cips.cardano.org/cips/cip1852/#derivationstyle).

2022-08-07 13:27 UTC, jleni commented
We've been participating of this discussion for a long time, including the alternative derivation path. However, there are many other factors to take into account, liability, custom extensions and modifications, maintenance costs, support, etc. This is much more than a mere and simple technical problem as a change in the derivation path.

Regardless, this PR will not work. This check is not the only place. In order to support a larger number of prefixes, Ledger needs to sign the app and allow the corresponding paths here:


Moreover, there is already an on-going exercise to unify things by using sign-mode textual.

We (zondax) will be discussing

2022-08-07 13:39 UTC, closed without merging

2022-08-07 13:40 UTC, liangping commented
Thanks @jleni. Let's close this PR for now.